/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.UpdateRate200ResponseDto;
import org.openapitools.model.UpdateRateDto;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "UpdateRate", description = "the UpdateRate API")
public interface UpdateRateApi {

    /**
     * POST /api/v1/rates : Update specific rate for spec date
     *
     * @param updateRateDto  (optional)
     * @return Update rate successful (status code 200)
     */
    @Operation(
        operationId = "updateRate",
        summary = "Update specific rate for spec date",
        tags = { "update-rate" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Update rate successful", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = UpdateRate200ResponseDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/v1/rates",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<UpdateRate200ResponseDto> updateRate(
        @Parameter(name = "UpdateRateDto", description = "") @Valid @RequestBody(required = false) UpdateRateDto updateRateDto
    );

}
