openapi: 3.0.0
info:
  title: My test
  description: My test description
  version: 1.0.0

paths:
  /api/v1/rates:
    get:
      tags:
        - get-rates
      summary: Get rates to USD
      operationId: getRates
      responses:
        '200':
          description: Get rates successful
          content:
            application/json:
              schema:
                $ref: 'dto/Rates.yaml'