apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32323
  selector:
    app: currency-service

#    http://localhost:8001/api/v1/namespaces/default/services/currency-service/proxy/api/v1/rates