apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
        - image: makstrexa/currency-service:1.0.9
          imagePullPolicy: Always
          name: currency-service
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
               name: currency-service-config
