apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: currency-service-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: "/api/v1"  # path: / -> http://{minikube_ip}/api/v1/rates
            pathType: "Prefix"
            backend:
              service:
                name: currency-service
                port:
                  number: 8080
